### ISSUE TITLE
tic_id error

### ISSUE THREAD

**Issue by LerhFengLow** [spacetelescope/hellouniverse#11]
I'm encountering an error when trying to use the "Classifying flaring stars with stella" notebook. The first two boxes run fine, but the third one complains of a tic_id error. What could be causing the problem?

![image](https://user-images.githubusercontent.com/53205850/183637320-145748cd-664f-403b-ac94-c5a4e5f2aea8.png)

**Comment by cmurray-astro** [comment]
thanks for submitting this issue! I think the problem has to do with your installation of `stella`. To confirm, which version of `stella` are you running?

**Comment by LerhFengLow** [comment]
How do I tell which version it is? I just reran `pip install stella` and the problem is still there, as well.

**Comment by cmurray-astro** [comment]
To check which version you are running, you can execute `print(stella.__version__)`

The issue you raised is fixed by installing the developer version of the `stella` package. I have updated the instructions for installing `stella` in the notebook. In your case, please re-install `stella` following their instructions for installing the developer version (https://adina.feinste.in/stella/getting_started/installation.html)

**Comment by LerhFengLow** [comment]
I ran the commands for installing the developer version but am still encountering the issue. The error message looks the same.

stella version is 0.0.5. That's an older version, right? The stella source code seems to say the most recent one is 0.1.0.

**Comment by cmurray-astro** [comment]
Thanks for sending this info! You will need to uninstall `stella` first (`pip uninstall stella`, for example, if you used pip to install initially). Then re-install using the instructions for installing the developer version. To verify, the version should be `0.2.0`.

**Comment by LerhFengLow** [comment]
It worked, thanks!
